# These are supported funding model platforms

github:
  - ackm04
  - erp-linker

patreon: erplinker


ko_fi: ackm04

<script type='text/javascript' src='https://storage.ko-fi.com/cdn/widget/Widget_2.js'></script><script type='text/javascript'>kofiwidget2.init('Support me on Ko-fi', '#72a4f2', 'X8X21WX8L9');kofiwidget2.draw();</script> 


buy_me_a_coffee: ackm

thanks_dev: ackm04
