# These are supported funding model platforms

github:
  - yourgithubusername
  - yourorgname

patreon: your_patreon_username

open_collective: your_open_collective_slug

ko_fi: your_kofi_username

tidelift: npm/your-package-name

community_bridge: your-project-name

liberapay: your_liberapay_username

issuehunt: your_issuehunt_username

lfx_crowdfunding: your-project-name

polar: your_polar_username

buy_me_a_coffee: your_bmac_username

thanks_dev: your_thanksdev_username

custom:
  - https://yourwebsite.com/sponsor
  - https://yourstripe-link.com
  - https://yourgumroad.com
  - https://yourpaypal.me
